import { Providers } from "./providers";
import Header from "./components/Header";
import "./styles/global.css";

export const metadata = {
  title: "Pixel Beanz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
